

nationality = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Botswana",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorian",
  "Egyptian",
  "Emirati",
  "Equatoguinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kiribati",
  "Korean",
  "Kosovar",
  "Kuwaiti",
  "Kyrgyzstani",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Lesotho",
  "Liberian",
  "Libyan",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Myanmar",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "Netherlands Antilles",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "Niuean",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Philippine",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Kitts and Nevis",
  "Saint Lucian",
  "Saint Vincentian",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Sint Maarten",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swazi",
]

neg_review= [
  "abysmal",
  "appalling",
  "atrocious",
  "awful",
  "bad",
  "beastly",
  "bitter",
  "bleak",
  "calamitous",
  "catastrophic",
  "chaotic",
  "crummy",
  "cruddy",
  "deplorable",
  "despicable",
  "detestable",
  "dire",
  "disastrous",
  "dismal",
  "dreadful",
  "dreary",
  "fearsome",
  "frightful",
  "ghastly",
  "gloomy",
  "grim",
  "harrowing",
  "hideous",
  "horrific",
  "horrible",
  "inept",
  "inexcusable",
  "infernal",
  "invidious",
  "lousy",
  "ludicrous",
  "malevolent",
  "mediocre",
  "miserable",
  "murky",
  "nasty",
  "nauseating",
  "obnoxious",
  "odious",
  "offensive",
  "okay",
  "oppressive",
  "painful",
  "pathetic",
  "pitiful",
  "poor",
  "preposterous",
  "rank",
  "regrettable",
  "repellent",
  "reprehensible",
  "repulsive",
  "revolting",
  "ridiculous",
  "rotten",
  "sad",
  "scandalous",
  "shabby",
  "shameful",
  "shocking",
  "sickening",
  "sinister",
  "sleazy",
  "slimy",
  "sordid",
  "sorry",
  "squalid",
  "stinking",
  "stormy",
  "tainted",
  "terrible",
  "the worst",
  "tormented",
  "torturous",
  "tragic",
  "troublesome",
  "ugly",
  "unacceptable",
  "unbearable",
  "unfortunate",
  "unhappy",
  "uninviting",
  "unpleasant",
  "unsatisfactory",
  "untoward",
  "unwelcome",
  "vile",
  "vulgar",
  "wicked",
  "woeful",
  "worrisome",
  "wretched",
  "wrong",
  "acceptable",
  "adequate",
  "all right",
  "average",
  "better",
  "decent",
  "fair",
  "fine",
  "good",
  "great",
  "impressive",
  "laudable",
  "nice",
  "not bad",
  "okay",
  "passable",
  "pleasant",
  "pleasing",
  "respectable",
  "satisfactory",
  "sufficient",
  "tolerable",
  "undistinguished",
  "unobjectionable",
  "welcome",
  "wonderful",
  "admirable",
  "amazing",
  "astonishing",
  "awe-inspiring",
  "brilliant",
  "commendable",
  "delightful",
  "distinguished",
  "exceptional",
  "excellent",
  "exquisite",
  "extraordinary",
  "fantastic",
  "flawless",
  "glorious",
  "gorgeous",
  "impeccable",
  "incredible",
  "inspiring",
  "lovely",
  "magnificent",
  "marvelous",
  "outstanding",
  "perfect",
  "phenomenal",]

pos_review = [
  "acceptable",
  "adequate",
  "all right",
  "average",
  "better",
  "commendable",
  "decent",
  "fair",
  "fine",
  "good",
  "impressive",
  "laudable",
  "nice",
  "not bad",
  "okay",
  "passable",
  "pleasant",
  "pleasing",
  "respectable",
  "satisfactory",
  "sufficient",
  "tolerable",
  "undistinguished",
  "unobjectionable",
  "welcome",
  "admirable",
  "amazing",
  "astonishing",
  "awe-inspiring",
  "awesome",
  "breathtaking",
  "brilliant",
  "captivating",
  "charming",
  "dazzling",
  "delightful",
  "distinguished",
  "exceptional",
  "excellent",
  "exquisite",
  "extraordinary",
  "fantastic",
  "flawless",
  "glorious",
  "gorgeous",
  "great",
  "impeccable",
  "incredible",
  "inspiring",
  "lovely",
  "magnificent",
  "marvelous",
  "outstanding",
  "perfect",
  "phenomenal",
  "remarkable",
  "sensational",
  "spectacular",
  "splendid",
  "stellar",
  "stunning",
  "superb",
  "terrific",
  "thrilling",
  "tremendous",
  "unbelievable",
  "unforgettable",
  "unparalleled",
  "unrivaled",
  "unsurpassed",
  "uplifting",
  "utterly fantastic",
  "wonderful"
]

trip_types=[
  "Adventure trip",
  "Backpacking trip",
  "Beach trip",
  "Business trip",
  "City break",
  "Couple",
  "Cruise trip",
  "Cultural trip",
  "Family trip",
  "Food and wine trip",
  "Friendship trip",
  "Gap year trip",
  "Girls' trip",
  "Guys' trip",
  "Honeymoon",
  "Leisure trip",
  "Luxury trip",
  "Mission trip",
  "Nature trip",
  "Pilgrimage",
  "Road trip",
  "Romantic getaway",
  "Senior trip",
  "Solo trip",
  "Sports trip",
  "Student trip",
  "Team-building trip",
  "Trekking trip",
  "Vacation",
  "Wellness trip",
  "Wildlife trip",
  "Winter sports trip",
  "Youth trip",
  "Anniversary trip",
  "Bachelor/bachelorette party",
  "Birthday trip",
  "Bucket list trip",
  "Camping trip",
  "Cycling trip",
  "Diving trip",
  "Eco-tourism trip",
  "Educational trip",
  "Exploration trip",
  "Festival trip",
  "Fishing trip",
  "Golf trip",
  "Hiking trip",
  "History trip",
  "Holiday trip",
  "Incentive trip",
  "Island trip",
  "Ladies' trip",
  "LGBTQ+ trip",
  "Milestone trip",
  "Motorcycle trip",
  "Music trip",
  "Outdoor adventure trip",
  "Photography trip",
  "Relaxation trip",
  "Religious trip",
  "Retreat trip",
  "Safari trip",
  "Scenic trip",
  "Shopping trip",
  "Skiing trip",
  "Spa trip",
  "Spiritual trip",
  "Sports fan trip",
  "Summer camp trip",
  "Theme park trip",
  "Tournament trip",
  "Volunteer trip",
  "Wedding trip",
  "Weekend getaway",
  "Wilderness trip",
  "Winter holiday trip",
  "Workation trip"
]